### ISSUE TITLE
IBM Storage Object Model link is broken

### ISSUE THREAD

**Issue by kdlucas** [IBM/ibm-cos-sdk-go#2]
Please fill out the sections below to help us address your issue.

### Version of AWS SDK for Go?
N/A

### Version of Go (`go version`)?
N/A

### What issue did you see?
Broken link is README.md

### Steps to reproduce
1. Click on IBM Cloud Object Storage in the README file:
https://github.com/IBM/ibm-cos-sdk-go/blob/master/README.md

If you have an runnable example, please include it.
This URL worked for me:
https://www.ibm.com/cloud/object-storage

**Comment by wbhuberIBM** [comment]
This has been fixed in Go Version 1.1.0.
