### ISSUE TITLE
Feature Request: Explicit server-side objects encryption with Key Protect(KP)

### ISSUE THREAD

**Issue by feliperfmarques** [IBM/ibm-cos-sdk-go#5]
### Is this related to a problem?

I have tried to pass an Key Protect root key CRN for `SSEKMSKeyId` parameter in s3.PutObjectInput method, but as I got an error, so I believe that this feature does not work.

* Code
```
	input := s3.PutObjectInput{
		Bucket:               aws.String("<MY_BUCKET>"),
		Key:                  aws.String("<MY_PREFIX>"),
		Body:                 bytes.NewReader(<MY_BODY>),
		ServerSideEncryption: aws.String("aws:kms"),
		SSEKMSKeyId:          aws.String("<MY_ROOT_KEY_CRN>"),
	}

```

* Error:
```
InvalidArgument: Requests specifying Server-Side Encryption with Customer-Provided Keys must provide an appropriate secret key.
```

### Feature description

I would like to encrypt specific objects on bucket using Key Protect, passing `SSEKMSKeyId` and `ServerSideEncryption` parameters for s3.PutObjectInput method, like this (in AWS S3):

https://docs.aws.amazon.com/sdk-for-go/v1/developer-guide/s3-example-server-side-encryption-with-kms.html

> "Note that this differs from Setting Default Server-Side Encryption for an ~~Amazon S3 Bucket~~ IBM COS Bucket, is in that case, the objects are encrypted without you having to explicitly perform the operation."

### Describe alternatives you've considered

Instead of using "aws:kms", could use the value "ibm:kp" for `ServerSideEncryption` parameter in the method.

**Comment by feliperfmarques** [comment]
@hkantare sorry for mentioning you, I don't know if you can help with this issue, but if not, could you to mention someone who can?

**Comment by IBMeric** [comment]
Happy new year! There is nothing wrong; the endpoints simply do not support the syntax you are trying to use. IBM released Key Protect before AWS, and their developers chose not include IBM's S3 extensions when making their own version.

I have passed your compatibility request to our internal roadmap team for consideration. In the meantime, you can find example documentation for using Key Protect with the Go SDK here: https://cloud.ibm.com/docs/cloud-object-storage?topic=cloud-object-storage-using-go#go-examples-kp.
